### ISSUE TITLE
PhpTikaWrapper

### ISSUE THREAD

**Issue by netidan** [pierroweb/PhpTikaWrapper#7]
hi
if i run the usage.php file trough ssh it works,
but it doesnt work in the browser, i just get an empty file.

**Comment by pierroweb** [comment]
You need to be able to execute shell commands through php.

Try the basic examples given in http://symfony.com/fr/doc/current/components/process.html from the browser.

**Comment by netidan** [comment]
ok i talked to my hosting and they said its security that blocking it. i order another server just for that and there it works.
thanks man :)
